services:
  - type: web
    name: sourcex-audit-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: workwithsourcex@gmail.com
      - key: FROM_NAME
        value: Vatsal | SOURCE X
      - key: NOTIFY_EMAIL
        value: workwithsourcex@gmail.com
